
image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - unset CI
    - BASE_PATH=624b1e8020abe90013dd5c9e/ npm run build
    - mv public public2
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
  